slice_name: AuditLoadingByErrors
description: null
certified_by: null
certification_details: null
viz_type: echarts_timeseries_bar
params:
  datasource: 15__table
  viz_type: echarts_timeseries_bar
  slice_id: 34
  x_axis: load_id
  xAxisForceCategorical: true
  x_axis_sort: SUM(errors)
  x_axis_sort_asc: false
  x_axis_sort_series: name
  x_axis_sort_series_ascending: true
  metrics:
  - aggregate: SUM
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: errors
      description: null
      expression: ''
      filterable: true
      groupby: true
      id: 84
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: LONGINTEGER
      type_generic: 0
      verbose_name: null
      warning_markdown: null
    datasourceWarning: false
    expressionType: SIMPLE
    hasCustomLabel: false
    label: SUM(errors)
    optionName: metric_fw5zf5xx6da_mdwizh5zax
    sqlExpression: null
  groupby: []
  adhoc_filters: []
  order_desc: true
  row_limit: 1000
  truncate_metric: true
  show_empty_columns: true
  comparison_type: values
  annotation_layers: []
  forecastPeriods: 10
  forecastInterval: 0.8
  orientation: vertical
  x_axis_title: load_id
  x_axis_title_margin: 30
  y_axis_title: Number of Errors
  y_axis_title_margin: 30
  y_axis_title_position: Top
  sort_series_type: sum
  color_scheme: redToYellow
  only_total: true
  minorTicks: false
  zoomable: false
  show_legend: true
  legendType: scroll
  legendOrientation: top
  x_axis_time_format: smart_date
  y_axis_format: SMART_NUMBER
  truncateXAxis: true
  y_axis_bounds:
  - null
  - null
  rich_tooltip: true
  showTooltipTotal: true
  showTooltipPercentage: true
  tooltipTimeFormat: smart_date
  extra_form_data: {}
  dashboards:
  - 4
query_context: '{"datasource": {"id": 15, "type": "table"}, "force": false, "queries":
  [{"filters": [], "extras": {"having": "", "where": ""}, "applied_time_extras": {},
  "columns": [{"columnType": "BASE_AXIS", "sqlExpression": "load_id", "label": "load_id",
  "expressionType": "SQL"}], "metrics": [{"aggregate": "SUM", "column": {"advanced_data_type":
  null, "certification_details": null, "certified_by": null, "column_name": "errors",
  "description": null, "expression": "", "filterable": true, "groupby": true, "id":
  84, "is_certified": false, "is_dttm": false, "python_date_format": null, "type":
  "LONGINTEGER", "type_generic": 0, "verbose_name": null, "warning_markdown": null},
  "datasourceWarning": false, "expressionType": "SIMPLE", "hasCustomLabel": false,
  "label": "SUM(errors)", "optionName": "metric_fw5zf5xx6da_mdwizh5zax", "sqlExpression":
  null}], "orderby": [[{"aggregate": "SUM", "column": {"advanced_data_type": null,
  "certification_details": null, "certified_by": null, "column_name": "errors", "description":
  null, "expression": "", "filterable": true, "groupby": true, "id": 84, "is_certified":
  false, "is_dttm": false, "python_date_format": null, "type": "LONGINTEGER", "type_generic":
  0, "verbose_name": null, "warning_markdown": null}, "datasourceWarning": false,
  "expressionType": "SIMPLE", "hasCustomLabel": false, "label": "SUM(errors)", "optionName":
  "metric_fw5zf5xx6da_mdwizh5zax", "sqlExpression": null}, false]], "annotation_layers":
  [], "row_limit": 1000, "series_columns": [], "series_limit": 0, "order_desc": true,
  "url_params": {}, "custom_params": {}, "custom_form_data": {}, "time_offsets": [],
  "post_processing": [{"operation": "pivot", "options": {"index": ["load_id"], "columns":
  [], "aggregates": {"SUM(errors)": {"operator": "mean"}}, "drop_missing_columns":
  false}}, {"operation": "sort", "options": {"by": "SUM(errors)", "ascending": false}},
  {"operation": "flatten"}]}], "form_data": {"datasource": "15__table", "viz_type":
  "echarts_timeseries_bar", "slice_id": 34, "x_axis": "load_id", "xAxisForceCategorical":
  true, "x_axis_sort": "SUM(errors)", "x_axis_sort_asc": false, "x_axis_sort_series":
  "name", "x_axis_sort_series_ascending": true, "metrics": [{"aggregate": "SUM", "column":
  {"advanced_data_type": null, "certification_details": null, "certified_by": null,
  "column_name": "errors", "description": null, "expression": "", "filterable": true,
  "groupby": true, "id": 84, "is_certified": false, "is_dttm": false, "python_date_format":
  null, "type": "LONGINTEGER", "type_generic": 0, "verbose_name": null, "warning_markdown":
  null}, "datasourceWarning": false, "expressionType": "SIMPLE", "hasCustomLabel":
  false, "label": "SUM(errors)", "optionName": "metric_fw5zf5xx6da_mdwizh5zax", "sqlExpression":
  null}], "groupby": [], "adhoc_filters": [], "order_desc": true, "row_limit": 1000,
  "truncate_metric": true, "show_empty_columns": true, "comparison_type": "values",
  "annotation_layers": [], "forecastPeriods": 10, "forecastInterval": 0.8, "orientation":
  "vertical", "x_axis_title": "load_id", "x_axis_title_margin": 30, "y_axis_title":
  "Number of Errors", "y_axis_title_margin": 30, "y_axis_title_position": "Top", "sort_series_type":
  "sum", "color_scheme": "redToYellow", "only_total": true, "minorTicks": false, "zoomable":
  false, "show_legend": true, "legendType": "scroll", "legendOrientation": "top",
  "x_axis_time_format": "smart_date", "y_axis_format": "SMART_NUMBER", "truncateXAxis":
  true, "y_axis_bounds": [null, null], "rich_tooltip": true, "showTooltipTotal": true,
  "showTooltipPercentage": true, "tooltipTimeFormat": "smart_date", "extra_form_data":
  {}, "dashboards": [4], "force": false, "result_format": "json", "result_type": "full"},
  "result_format": "json", "result_type": "full"}'
cache_timeout: null
uuid: 4b4e619a-4a3b-425c-9522-7f47d8a4e940
version: 1.0.0
dataset_uuid: cc2f4346-2ddf-41c8-9c85-d611baeb8b81
