slice_name: AuditLoadingProcessesNumber
description: null
certified_by: null
certification_details: null
viz_type: big_number_total
params:
  datasource: 12__table
  viz_type: big_number_total
  metric:
    expressionType: SIMPLE
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: load_id
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 52
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: INTEGER
      type_generic: 0
      verbose_name: null
      warning_markdown: null
    aggregate: COUNT
    sqlExpression: null
    datasourceWarning: false
    hasCustomLabel: false
    label: COUNT(load_id)
    optionName: metric_m16ki74ro9_c0g3bs64cxm
  adhoc_filters:
  - clause: WHERE
    subject: start_time
    operator: TEMPORAL_RANGE
    comparator: No filter
    expressionType: SIMPLE
  subheader: '#Loading Processes'
  header_font_size: 0.6
  subheader_font_size: 0.125
  y_axis_format: SMART_NUMBER
  time_format: smart_date
  conditional_formatting: []
  extra_form_data: {}
  dashboards:
  - 4
  annotation_layers: []
query_context: '{"datasource": {"id": 12, "type": "table"}, "force": false, "queries":
  [{"filters": [{"col": "start_time", "op": "TEMPORAL_RANGE", "val": "No filter"}],
  "extras": {"having": "", "where": ""}, "applied_time_extras": {}, "columns": [],
  "metrics": [{"expressionType": "SIMPLE", "column": {"advanced_data_type": null,
  "certification_details": null, "certified_by": null, "column_name": "load_id", "description":
  null, "expression": null, "filterable": true, "groupby": true, "id": 52, "is_certified":
  false, "is_dttm": false, "python_date_format": null, "type": "INTEGER", "type_generic":
  0, "verbose_name": null, "warning_markdown": null}, "aggregate": "COUNT", "sqlExpression":
  null, "datasourceWarning": false, "hasCustomLabel": false, "label": "COUNT(load_id)",
  "optionName": "metric_m16ki74ro9_c0g3bs64cxm"}], "annotation_layers": [], "series_limit":
  0, "order_desc": true, "url_params": {}, "custom_params": {}, "custom_form_data":
  {}}], "form_data": {"datasource": "12__table", "viz_type": "big_number_total", "metric":
  {"expressionType": "SIMPLE", "column": {"advanced_data_type": null, "certification_details":
  null, "certified_by": null, "column_name": "load_id", "description": null, "expression":
  null, "filterable": true, "groupby": true, "id": 52, "is_certified": false, "is_dttm":
  false, "python_date_format": null, "type": "INTEGER", "type_generic": 0, "verbose_name":
  null, "warning_markdown": null}, "aggregate": "COUNT", "sqlExpression": null, "datasourceWarning":
  false, "hasCustomLabel": false, "label": "COUNT(load_id)", "optionName": "metric_m16ki74ro9_c0g3bs64cxm"},
  "adhoc_filters": [{"clause": "WHERE", "subject": "start_time", "operator": "TEMPORAL_RANGE",
  "comparator": "No filter", "expressionType": "SIMPLE"}], "subheader": "#Loading
  Processes", "header_font_size": 0.6, "subheader_font_size": 0.125, "y_axis_format":
  "SMART_NUMBER", "time_format": "smart_date", "conditional_formatting": [], "extra_form_data":
  {}, "dashboards": [4], "force": false, "result_format": "json", "result_type": "full"},
  "result_format": "json", "result_type": "full"}'
cache_timeout: null
uuid: 590853b8-0c56-4ee2-87b6-c9c57439796a
version: 1.0.0
dataset_uuid: b0aec369-c7a3-4403-878b-97d8f77b890c
