slice_name: CurrencyAmountSummary
description: null
certified_by: null
certification_details: null
viz_type: table
params:
  datasource: 1__table
  viz_type: table
  slice_id: 8
  query_mode: aggregate
  groupby:
  - currency_code
  temporal_columns_lookup:
    date: true
  metrics:
  - expressionType: SQL
    sqlExpression: COUNT(amount)
    column: null
    aggregate: null
    datasourceWarning: false
    hasCustomLabel: false
    label: COUNT(amount)
    optionName: metric_gmlotwf6ygm_kyroies6ee
  - expressionType: SIMPLE
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: amount
      description: null
      expression: ''
      filterable: true
      groupby: true
      id: 14
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: DECIMAL
      type_generic: 0
      verbose_name: null
      warning_markdown: null
    aggregate: SUM
    sqlExpression: null
    datasourceWarning: false
    hasCustomLabel: false
    label: SUM(amount)
    optionName: metric_mm61rfob25b_2fsab5op6h3
  all_columns:
  - currency_code
  - amount
  percent_metrics:
  - expressionType: SIMPLE
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: amount
      description: null
      expression: ''
      filterable: true
      groupby: true
      id: 14
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: DECIMAL
      type_generic: 0
      verbose_name: null
      warning_markdown: null
    aggregate: COUNT
    sqlExpression: null
    datasourceWarning: false
    hasCustomLabel: false
    label: COUNT(amount)
    optionName: metric_jmxv25r152_o9swy0fqyr9
  adhoc_filters:
  - clause: WHERE
    comparator: No filter
    expressionType: SIMPLE
    operator: TEMPORAL_RANGE
    subject: date
  timeseries_limit_metric:
    aggregate: COUNT
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: amount
      description: null
      expression: ''
      filterable: true
      groupby: true
      id: 14
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: DECIMAL
      type_generic: 0
      verbose_name: null
      warning_markdown: null
    datasourceWarning: false
    expressionType: SIMPLE
    hasCustomLabel: false
    label: COUNT(amount)
    optionName: metric_grhsp2qsgfq_rtimlgt7c9o
    sqlExpression: null
  order_by_cols: []
  row_limit: 1000
  order_desc: true
  table_timestamp_format: smart_date
  allow_render_html: true
  show_cell_bars: true
  color_pn: true
  comparison_color_scheme: Green
  comparison_type: values
  extra_form_data: {}
  dashboards:
  - 1
  annotation_layers: []
query_context: '{"datasource":{"id":1,"type":"table"},"force":false,"queries":[{"filters":[{"col":"date","op":"TEMPORAL_RANGE","val":"No
  filter"}],"extras":{"having":"","where":""},"applied_time_extras":{},"columns":["currency_code"],"metrics":[{"expressionType":"SQL","sqlExpression":"COUNT(amount)","column":null,"aggregate":null,"datasourceWarning":false,"hasCustomLabel":false,"label":"COUNT(amount)","optionName":"metric_gmlotwf6ygm_kyroies6ee"},{"expressionType":"SIMPLE","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"amount","description":null,"expression":"","filterable":true,"groupby":true,"id":14,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"DECIMAL","type_generic":0,"verbose_name":null,"warning_markdown":null},"aggregate":"SUM","sqlExpression":null,"datasourceWarning":false,"hasCustomLabel":false,"label":"SUM(amount)","optionName":"metric_mm61rfob25b_2fsab5op6h3"}],"orderby":[[{"aggregate":"COUNT","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"amount","description":null,"expression":"","filterable":true,"groupby":true,"id":14,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"DECIMAL","type_generic":0,"verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":false,"label":"COUNT(amount)","optionName":"metric_grhsp2qsgfq_rtimlgt7c9o","sqlExpression":null},false]],"annotation_layers":[],"row_limit":1000,"series_limit":0,"series_limit_metric":{"aggregate":"COUNT","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"amount","description":null,"expression":"","filterable":true,"groupby":true,"id":14,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"DECIMAL","type_generic":0,"verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":false,"label":"COUNT(amount)","optionName":"metric_grhsp2qsgfq_rtimlgt7c9o","sqlExpression":null},"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{},"post_processing":[{"operation":"contribution","options":{"columns":["COUNT(amount)"],"rename_columns":["%COUNT(amount)"]}}],"time_offsets":[]}],"form_data":{"datasource":"1__table","viz_type":"table","slice_id":8,"query_mode":"aggregate","groupby":["currency_code"],"temporal_columns_lookup":{"date":true},"metrics":[{"expressionType":"SQL","sqlExpression":"COUNT(amount)","column":null,"aggregate":null,"datasourceWarning":false,"hasCustomLabel":false,"label":"COUNT(amount)","optionName":"metric_gmlotwf6ygm_kyroies6ee"},{"expressionType":"SIMPLE","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"amount","description":null,"expression":"","filterable":true,"groupby":true,"id":14,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"DECIMAL","type_generic":0,"verbose_name":null,"warning_markdown":null},"aggregate":"SUM","sqlExpression":null,"datasourceWarning":false,"hasCustomLabel":false,"label":"SUM(amount)","optionName":"metric_mm61rfob25b_2fsab5op6h3"}],"all_columns":["currency_code","amount"],"percent_metrics":[{"expressionType":"SIMPLE","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"amount","description":null,"expression":"","filterable":true,"groupby":true,"id":14,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"DECIMAL","type_generic":0,"verbose_name":null,"warning_markdown":null},"aggregate":"COUNT","sqlExpression":null,"datasourceWarning":false,"hasCustomLabel":false,"label":"COUNT(amount)","optionName":"metric_jmxv25r152_o9swy0fqyr9"}],"adhoc_filters":[{"clause":"WHERE","comparator":"No
  filter","expressionType":"SIMPLE","operator":"TEMPORAL_RANGE","subject":"date"}],"timeseries_limit_metric":{"aggregate":"COUNT","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"amount","description":null,"expression":"","filterable":true,"groupby":true,"id":14,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"DECIMAL","type_generic":0,"verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":false,"label":"COUNT(amount)","optionName":"metric_grhsp2qsgfq_rtimlgt7c9o","sqlExpression":null},"order_by_cols":[],"row_limit":1000,"order_desc":true,"table_timestamp_format":"smart_date","allow_render_html":true,"show_cell_bars":true,"color_pn":true,"comparison_color_scheme":"Green","comparison_type":"values","extra_form_data":{},"dashboards":[1],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: 7cf7ed81-e60d-429e-b650-c6f6721a39b7
version: 1.0.0
dataset_uuid: 4afb8409-9d20-49b2-8791-d74b58810204
