slice_name: MDCurrencies
description: null
certified_by: null
certification_details: null
viz_type: table
params:
  datasource: 7__table
  viz_type: table
  query_mode: raw
  groupby: []
  time_grain_sqla: P1D
  temporal_columns_lookup: {}
  all_columns:
  - label: currency_id
    sqlExpression: currency_id::VARCHAR(50)
    expressionType: SQL
  - currency_code
  - currency_name
  percent_metrics: []
  adhoc_filters: []
  order_by_cols: []
  row_limit: 1000
  server_page_length: 10
  order_desc: true
  table_timestamp_format: smart_date
  allow_render_html: true
  show_cell_bars: true
  color_pn: true
  comparison_color_scheme: Green
  comparison_type: values
  extra_form_data: {}
  dashboards: []
  annotation_layers: []
query_context: '{"datasource":{"id":7,"type":"table"},"force":false,"queries":[{"filters":[],"extras":{"having":"","where":""},"applied_time_extras":{},"columns":[{"label":"currency_id","sqlExpression":"currency_id::VARCHAR(50)","expressionType":"SQL"},"currency_code","currency_name"],"orderby":[],"annotation_layers":[],"row_limit":1000,"series_limit":0,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{},"post_processing":[],"time_offsets":[]}],"form_data":{"datasource":"7__table","viz_type":"table","query_mode":"raw","groupby":[],"time_grain_sqla":"P1D","temporal_columns_lookup":{},"all_columns":[{"label":"currency_id","sqlExpression":"currency_id::VARCHAR(50)","expressionType":"SQL"},"currency_code","currency_name"],"percent_metrics":[],"adhoc_filters":[],"order_by_cols":[],"row_limit":1000,"server_page_length":10,"order_desc":true,"table_timestamp_format":"smart_date","allow_render_html":true,"show_cell_bars":true,"color_pn":true,"comparison_color_scheme":"Green","comparison_type":"values","extra_form_data":{},"dashboards":[],"force":false,"result_format":"json","result_type":"full","include_time":false},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: fb1d5318-d71d-48ea-a23b-952f4fd09b27
version: 1.0.0
dataset_uuid: 9ef40a5c-3aea-403c-b181-a2bbc7f32d66
