slice_name: MDTransactionValidationRules
description: null
certified_by: null
certification_details: null
viz_type: table
params:
  datasource: 6__table
  viz_type: table
  query_mode: raw
  groupby: []
  time_grain_sqla: P1D
  temporal_columns_lookup:
    created_at: true
    updated_at: true
  all_columns:
  - label: id
    sqlExpression: id::VARCHAR(50)
    expressionType: SQL
  - rule_type
  - rule_description
  - params
  - violation_severity
  - active
  - created_at
  - updated_at
  percent_metrics: []
  adhoc_filters:
  - clause: WHERE
    subject: created_at
    operator: TEMPORAL_RANGE
    comparator: No filter
    expressionType: SIMPLE
  order_by_cols: []
  row_limit: 1000
  server_page_length: 10
  order_desc: true
  table_timestamp_format: smart_date
  allow_render_html: true
  column_config:
    created_at:
      d3TimeFormat: '%Y-%m-%d %H:%M:%S'
    updated_at:
      d3TimeFormat: '%Y-%m-%d %H:%M:%S'
  show_cell_bars: true
  color_pn: true
  comparison_color_scheme: Green
  conditional_formatting: []
  comparison_type: values
  extra_form_data: {}
  dashboards: []
  annotation_layers: []
query_context: '{"datasource":{"id":6,"type":"table"},"force":false,"queries":[{"filters":[{"col":"created_at","op":"TEMPORAL_RANGE","val":"No
  filter"}],"extras":{"having":"","where":""},"applied_time_extras":{},"columns":[{"label":"id","sqlExpression":"id::VARCHAR(50)","expressionType":"SQL"},"rule_type","rule_description","params","violation_severity","active","created_at","updated_at"],"orderby":[],"annotation_layers":[],"row_limit":1000,"series_limit":0,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{},"post_processing":[],"time_offsets":[]}],"form_data":{"datasource":"6__table","viz_type":"table","query_mode":"raw","groupby":[],"time_grain_sqla":"P1D","temporal_columns_lookup":{"created_at":true,"updated_at":true},"all_columns":[{"label":"id","sqlExpression":"id::VARCHAR(50)","expressionType":"SQL"},"rule_type","rule_description","params","violation_severity","active","created_at","updated_at"],"percent_metrics":[],"adhoc_filters":[{"clause":"WHERE","subject":"created_at","operator":"TEMPORAL_RANGE","comparator":"No
  filter","expressionType":"SIMPLE"}],"order_by_cols":[],"row_limit":1000,"server_page_length":10,"order_desc":true,"table_timestamp_format":"smart_date","allow_render_html":true,"column_config":{"created_at":{"d3TimeFormat":"%Y-%m-%d
  %H:%M:%S"},"updated_at":{"d3TimeFormat":"%Y-%m-%d %H:%M:%S"}},"show_cell_bars":true,"color_pn":true,"comparison_color_scheme":"Green","conditional_formatting":[],"comparison_type":"values","extra_form_data":{},"dashboards":[],"force":false,"result_format":"json","result_type":"full","include_time":false},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: 7f930dad-e3fa-400d-8c22-8872f65823c7
version: 1.0.0
dataset_uuid: 9155bdbf-4d56-47d2-b7df-00c5866ef53e
