slice_name: NetFlowByCurrency30d
description: null
certified_by: null
certification_details: null
viz_type: echarts_timeseries_bar
params:
  datasource: 17__table
  viz_type: echarts_timeseries_bar
  x_axis: user
  x_axis_sort_series: name
  x_axis_sort_series_ascending: true
  metrics:
  - expressionType: SIMPLE
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: net_flow
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 97
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: DECIMAL
      type_generic: 0
      verbose_name: null
      warning_markdown: null
    aggregate: SUM
    sqlExpression: null
    datasourceWarning: false
    hasCustomLabel: false
    label: SUM(net_flow)
    optionName: metric_i0qwpbo7iv9_i6iifc14qu
  groupby:
  - currency_code
  adhoc_filters: []
  row_limit: 1000
  truncate_metric: true
  show_empty_columns: true
  annotation_layers: []
  orientation: horizontal
  x_axis_title: ''
  x_axis_title_margin: 15
  y_axis_title: Net Flow
  y_axis_title_margin: 30
  y_axis_title_position: Left
  sort_series_type: sum
  color_scheme: googleCategory20c
  show_value: false
  show_legend: true
  legendType: scroll
  legendOrientation: top
  x_axis_time_format: smart_date
  y_axis_format: SMART_NUMBER
  logAxis: false
  minorSplitLine: false
  truncateXAxis: true
  truncateYAxis: false
  y_axis_bounds:
  - null
  - null
  rich_tooltip: true
  showTooltipTotal: true
  showTooltipPercentage: true
  tooltipTimeFormat: smart_date
  extra_form_data: {}
  dashboards: []
query_context: '{"datasource":{"id":17,"type":"table"},"force":false,"queries":[{"filters":[],"extras":{"having":"","where":""},"applied_time_extras":{},"columns":[{"columnType":"BASE_AXIS","sqlExpression":"user","label":"user","expressionType":"SQL"},"currency_code"],"metrics":[{"expressionType":"SIMPLE","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"net_flow","description":null,"expression":null,"filterable":true,"groupby":true,"id":97,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"DECIMAL","type_generic":0,"verbose_name":null,"warning_markdown":null},"aggregate":"SUM","sqlExpression":null,"datasourceWarning":false,"hasCustomLabel":false,"label":"SUM(net_flow)","optionName":"metric_i0qwpbo7iv9_i6iifc14qu"}],"orderby":[[{"expressionType":"SIMPLE","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"net_flow","description":null,"expression":null,"filterable":true,"groupby":true,"id":97,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"DECIMAL","type_generic":0,"verbose_name":null,"warning_markdown":null},"aggregate":"SUM","sqlExpression":null,"datasourceWarning":false,"hasCustomLabel":false,"label":"SUM(net_flow)","optionName":"metric_i0qwpbo7iv9_i6iifc14qu"},false]],"annotation_layers":[],"row_limit":1000,"series_columns":["currency_code"],"series_limit":0,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{},"time_offsets":[],"post_processing":[{"operation":"pivot","options":{"index":["user"],"columns":["currency_code"],"aggregates":{"SUM(net_flow)":{"operator":"mean"}},"drop_missing_columns":false}},{"operation":"rename","options":{"columns":{"SUM(net_flow)":null},"level":0,"inplace":true}},{"operation":"flatten"}]}],"form_data":{"datasource":"17__table","viz_type":"echarts_timeseries_bar","x_axis":"user","x_axis_sort_series":"name","x_axis_sort_series_ascending":true,"metrics":[{"expressionType":"SIMPLE","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"net_flow","description":null,"expression":null,"filterable":true,"groupby":true,"id":97,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"DECIMAL","type_generic":0,"verbose_name":null,"warning_markdown":null},"aggregate":"SUM","sqlExpression":null,"datasourceWarning":false,"hasCustomLabel":false,"label":"SUM(net_flow)","optionName":"metric_i0qwpbo7iv9_i6iifc14qu"}],"groupby":["currency_code"],"adhoc_filters":[],"row_limit":1000,"truncate_metric":true,"show_empty_columns":true,"annotation_layers":[],"orientation":"horizontal","x_axis_title":"","x_axis_title_margin":15,"y_axis_title":"Net
  Flow","y_axis_title_margin":30,"y_axis_title_position":"Left","sort_series_type":"sum","color_scheme":"googleCategory20c","show_value":false,"show_legend":true,"legendType":"scroll","legendOrientation":"top","x_axis_time_format":"smart_date","y_axis_format":"SMART_NUMBER","logAxis":false,"minorSplitLine":false,"truncateXAxis":true,"truncateYAxis":false,"y_axis_bounds":[null,null],"rich_tooltip":true,"showTooltipTotal":true,"showTooltipPercentage":true,"tooltipTimeFormat":"smart_date","extra_form_data":{},"dashboards":[],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: 51267fbb-869c-4c6d-b57a-7124677c4c6d
version: 1.0.0
dataset_uuid: 74b6a1e4-e5f9-4ea9-af56-355f429cb7ec
