slice_name: Top5TransactionsDay
description: null
certified_by: null
certification_details: null
viz_type: table
params:
  datasource: 2__table
  viz_type: table
  query_mode: aggregate
  groupby:
  - date
  time_grain_sqla: P1D
  temporal_columns_lookup:
    date: true
  metrics:
  - expressionType: SIMPLE
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: transactions
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 6
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: LONGINTEGER
      type_generic: 0
      verbose_name: null
      warning_markdown: null
    aggregate: SUM
    sqlExpression: null
    datasourceWarning: false
    hasCustomLabel: false
    label: SUM(transactions)
    optionName: metric_pmqsvngn048_rq7gdf24wx
  all_columns:
  - date
  - transactions
  percent_metrics: []
  adhoc_filters:
  - clause: WHERE
    subject: date
    operator: TEMPORAL_RANGE
    comparator: No filter
    expressionType: SIMPLE
  order_by_cols: []
  row_limit: 10000
  order_desc: true
  table_timestamp_format: smart_date
  allow_render_html: true
  column_config:
    SUM(transactions):
      horizontalAlign: left
      colorPositiveNegative: true
  show_cell_bars: true
  color_pn: true
  conditional_formatting: []
  comparison_type: values
  extra_form_data: {}
  dashboards: []
  annotation_layers: []
query_context: '{"datasource":{"id":2,"type":"table"},"force":false,"queries":[{"filters":[{"col":"date","op":"TEMPORAL_RANGE","val":"No
  filter"}],"extras":{"time_grain_sqla":"P1D","having":"","where":""},"applied_time_extras":{},"columns":[{"timeGrain":"P1D","columnType":"BASE_AXIS","sqlExpression":"date","label":"date","expressionType":"SQL"}],"metrics":[{"expressionType":"SIMPLE","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"transactions","description":null,"expression":null,"filterable":true,"groupby":true,"id":6,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"LONGINTEGER","type_generic":0,"verbose_name":null,"warning_markdown":null},"aggregate":"SUM","sqlExpression":null,"datasourceWarning":false,"hasCustomLabel":false,"label":"SUM(transactions)","optionName":"metric_pmqsvngn048_rq7gdf24wx"}],"orderby":[[{"expressionType":"SIMPLE","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"transactions","description":null,"expression":null,"filterable":true,"groupby":true,"id":6,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"LONGINTEGER","type_generic":0,"verbose_name":null,"warning_markdown":null},"aggregate":"SUM","sqlExpression":null,"datasourceWarning":false,"hasCustomLabel":false,"label":"SUM(transactions)","optionName":"metric_pmqsvngn048_rq7gdf24wx"},false]],"annotation_layers":[],"row_limit":10000,"series_limit":0,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{},"post_processing":[],"time_offsets":[]}],"form_data":{"datasource":"2__table","viz_type":"table","query_mode":"aggregate","groupby":["date"],"time_grain_sqla":"P1D","temporal_columns_lookup":{"date":true},"metrics":[{"expressionType":"SIMPLE","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"transactions","description":null,"expression":null,"filterable":true,"groupby":true,"id":6,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"LONGINTEGER","type_generic":0,"verbose_name":null,"warning_markdown":null},"aggregate":"SUM","sqlExpression":null,"datasourceWarning":false,"hasCustomLabel":false,"label":"SUM(transactions)","optionName":"metric_pmqsvngn048_rq7gdf24wx"}],"all_columns":["date","transactions"],"percent_metrics":[],"adhoc_filters":[{"clause":"WHERE","subject":"date","operator":"TEMPORAL_RANGE","comparator":"No
  filter","expressionType":"SIMPLE"}],"order_by_cols":[],"row_limit":10000,"order_desc":true,"table_timestamp_format":"smart_date","allow_render_html":true,"column_config":{"SUM(transactions)":{"horizontalAlign":"left","colorPositiveNegative":true}},"show_cell_bars":true,"color_pn":true,"conditional_formatting":[],"comparison_type":"values","extra_form_data":{},"dashboards":[],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: 32a7cf00-540c-490a-8b02-f210694358a0
version: 1.0.0
dataset_uuid: 2ca2d1e7-8d29-4d40-be72-d80853a5d031
