slice_name: TotalTransactions30d
description: null
certified_by: null
certification_details: null
viz_type: big_number_total
params:
  datasource: 1__table
  viz_type: big_number_total
  slice_id: 2
  metric:
    aggregate: COUNT
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: amount
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 4
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: DECIMAL
      type_generic: 0
      verbose_name: null
      warning_markdown: null
    datasourceWarning: false
    expressionType: SIMPLE
    hasCustomLabel: false
    label: COUNT(amount)
    optionName: metric_3fwvmmw0e6b_evkwpr4lzwa
    sqlExpression: null
  adhoc_filters:
  - clause: WHERE
    comparator: Last month
    datasourceWarning: false
    expressionType: SIMPLE
    filterOptionName: filter_0zj3k7qhqkeh_381runj2lk4
    isExtra: false
    isNew: false
    operator: TEMPORAL_RANGE
    sqlExpression: null
    subject: date
  subheader: '#Transactions 30d'
  header_font_size: 0.6
  subheader_font_size: 0.15
  y_axis_format: SMART_NUMBER
  time_format: smart_date
  conditional_formatting: []
  extra_form_data: {}
  dashboards:
  - 1
  annotation_layers: []
query_context: '{"datasource":{"id":1,"type":"table"},"force":false,"queries":[{"filters":[{"col":"date","op":"TEMPORAL_RANGE","val":"Last
  month"}],"extras":{"having":"","where":""},"applied_time_extras":{},"columns":[],"metrics":[{"aggregate":"COUNT","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"amount","description":null,"expression":null,"filterable":true,"groupby":true,"id":4,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"DECIMAL","type_generic":0,"verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":false,"label":"COUNT(amount)","optionName":"metric_3fwvmmw0e6b_evkwpr4lzwa","sqlExpression":null}],"annotation_layers":[],"series_limit":0,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{}}],"form_data":{"datasource":"1__table","viz_type":"big_number_total","slice_id":2,"metric":{"aggregate":"COUNT","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"amount","description":null,"expression":null,"filterable":true,"groupby":true,"id":4,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"DECIMAL","type_generic":0,"verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":false,"label":"COUNT(amount)","optionName":"metric_3fwvmmw0e6b_evkwpr4lzwa","sqlExpression":null},"adhoc_filters":[{"clause":"WHERE","comparator":"Last
  month","datasourceWarning":false,"expressionType":"SIMPLE","filterOptionName":"filter_0zj3k7qhqkeh_381runj2lk4","isExtra":false,"isNew":false,"operator":"TEMPORAL_RANGE","sqlExpression":null,"subject":"date"}],"subheader":"#Transactions
  30d","header_font_size":0.6,"subheader_font_size":0.15,"y_axis_format":"SMART_NUMBER","time_format":"smart_date","conditional_formatting":[],"extra_form_data":{},"dashboards":[1],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: 43980638-2c63-4b0f-b576-7137b0f8b6d0
version: 1.0.0
dataset_uuid: 4afb8409-9d20-49b2-8791-d74b58810204
