slice_name: TransactonsCurrencyByAgeDecade
description: null
certified_by: null
certification_details: null
viz_type: echarts_timeseries_bar
params:
  datasource: 10__table
  viz_type: echarts_timeseries_bar
  slice_id: 22
  x_axis: sender_age_bucket_decade
  x_axis_sort_asc: true
  x_axis_sort_series: name
  x_axis_sort_series_ascending: true
  metrics:
  - aggregate: COUNT
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: amount
      description: null
      expression: ''
      filterable: true
      groupby: true
      id: 48
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: DECIMAL
      type_generic: 0
      verbose_name: null
      warning_markdown: null
    datasourceWarning: false
    expressionType: SIMPLE
    hasCustomLabel: false
    label: COUNT(amount)
    optionName: metric_aypdngx3my7_zb4592zi9ua
    sqlExpression: null
  groupby:
  - currency_code
  adhoc_filters:
  - clause: WHERE
    comparator: No filter
    expressionType: SIMPLE
    operator: TEMPORAL_RANGE
    subject: date
  order_desc: true
  row_limit: 50000
  truncate_metric: true
  show_empty_columns: true
  comparison_type: values
  annotation_layers: []
  forecastPeriods: 10
  forecastInterval: 0.8
  orientation: vertical
  x_axis_title: Age Decade
  x_axis_title_margin: 30
  y_axis_title: '# Transactions'
  y_axis_title_margin: 30
  y_axis_title_position: Top
  sort_series_type: sum
  color_scheme: supersetColors
  show_value: true
  only_total: true
  minorTicks: true
  zoomable: true
  show_legend: true
  legendType: scroll
  legendOrientation: top
  x_axis_time_format: smart_date
  y_axis_format: SMART_NUMBER
  truncateXAxis: true
  y_axis_bounds:
  - null
  - null
  rich_tooltip: true
  showTooltipTotal: true
  showTooltipPercentage: true
  tooltipTimeFormat: smart_date
  extra_form_data: {}
  dashboards:
  - 3
query_context: '{"datasource":{"id":10,"type":"table"},"force":false,"queries":[{"filters":[{"col":"date","op":"TEMPORAL_RANGE","val":"No
  filter"}],"extras":{"having":"","where":""},"applied_time_extras":{},"columns":[{"columnType":"BASE_AXIS","sqlExpression":"sender_age_bucket_decade","label":"sender_age_bucket_decade","expressionType":"SQL"},"currency_code"],"metrics":[{"aggregate":"COUNT","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"amount","description":null,"expression":"","filterable":true,"groupby":true,"id":48,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"DECIMAL","type_generic":0,"verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":false,"label":"COUNT(amount)","optionName":"metric_aypdngx3my7_zb4592zi9ua","sqlExpression":null}],"orderby":[[{"aggregate":"COUNT","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"amount","description":null,"expression":"","filterable":true,"groupby":true,"id":48,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"DECIMAL","type_generic":0,"verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":false,"label":"COUNT(amount)","optionName":"metric_aypdngx3my7_zb4592zi9ua","sqlExpression":null},false]],"annotation_layers":[],"row_limit":50000,"series_columns":["currency_code"],"series_limit":0,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{},"time_offsets":[],"post_processing":[{"operation":"pivot","options":{"index":["sender_age_bucket_decade"],"columns":["currency_code"],"aggregates":{"COUNT(amount)":{"operator":"mean"}},"drop_missing_columns":false}},{"operation":"rename","options":{"columns":{"COUNT(amount)":null},"level":0,"inplace":true}},{"operation":"flatten"}]}],"form_data":{"datasource":"10__table","viz_type":"echarts_timeseries_bar","slice_id":22,"x_axis":"sender_age_bucket_decade","x_axis_sort_asc":true,"x_axis_sort_series":"name","x_axis_sort_series_ascending":true,"metrics":[{"aggregate":"COUNT","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"amount","description":null,"expression":"","filterable":true,"groupby":true,"id":48,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"DECIMAL","type_generic":0,"verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":false,"label":"COUNT(amount)","optionName":"metric_aypdngx3my7_zb4592zi9ua","sqlExpression":null}],"groupby":["currency_code"],"adhoc_filters":[{"clause":"WHERE","comparator":"No
  filter","expressionType":"SIMPLE","operator":"TEMPORAL_RANGE","subject":"date"}],"order_desc":true,"row_limit":50000,"truncate_metric":true,"show_empty_columns":true,"comparison_type":"values","annotation_layers":[],"forecastPeriods":10,"forecastInterval":0.8,"orientation":"vertical","x_axis_title":"Age
  Decade","x_axis_title_margin":30,"y_axis_title":"# Transactions","y_axis_title_margin":30,"y_axis_title_position":"Top","sort_series_type":"sum","color_scheme":"supersetColors","show_value":true,"only_total":true,"minorTicks":true,"zoomable":true,"show_legend":true,"legendType":"scroll","legendOrientation":"top","x_axis_time_format":"smart_date","y_axis_format":"SMART_NUMBER","truncateXAxis":true,"y_axis_bounds":[null,null],"rich_tooltip":true,"showTooltipTotal":true,"showTooltipPercentage":true,"tooltipTimeFormat":"smart_date","extra_form_data":{},"dashboards":[3],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: 9a47918f-cadd-4e81-add5-8ff37ab8eb64
version: 1.0.0
dataset_uuid: 5a804353-d143-4c74-aa5f-60a7d5ced6e2
