slice_name: TransactionsByDayOfWeek
description: null
certified_by: null
certification_details: null
viz_type: echarts_timeseries_bar
params:
  datasource: 1__table
  viz_type: echarts_timeseries_bar
  slice_id: 7
  x_axis: day_name
  xAxisForceCategorical: true
  x_axis_sort: COUNT(amount)
  x_axis_sort_asc: false
  metrics:
  - aggregate: COUNT
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: amount
      description: null
      expression: ''
      filterable: true
      groupby: true
      id: 13
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: DECIMAL
      type_generic: 0
      verbose_name: null
      warning_markdown: null
    datasourceWarning: false
    expressionType: SIMPLE
    hasCustomLabel: false
    label: COUNT(amount)
    optionName: metric_6efvc4reoji_dszmsh7t3un
    sqlExpression: null
  groupby: []
  adhoc_filters:
  - clause: WHERE
    comparator: No filter
    expressionType: SIMPLE
    operator: TEMPORAL_RANGE
    subject: date
  timeseries_limit_metric:
    aggregate: COUNT
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: amount
      description: null
      expression: ''
      filterable: true
      groupby: true
      id: 13
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: DECIMAL
      type_generic: 0
      verbose_name: null
      warning_markdown: null
    datasourceWarning: false
    expressionType: SIMPLE
    hasCustomLabel: false
    label: COUNT(amount)
    optionName: metric_xzyztao0twa_acxudg9kwz
    sqlExpression: null
  order_desc: true
  row_limit: 10000
  truncate_metric: true
  show_empty_columns: true
  annotation_layers: []
  orientation: vertical
  x_axis_title: Day of the Week
  x_axis_title_margin: 30
  y_axis_title: '#Transactions'
  y_axis_title_margin: 30
  y_axis_title_position: Left
  sort_series_type: sum
  color_scheme: redToYellow
  show_value: true
  show_legend: false
  x_axis_time_format: smart_date
  y_axis_format: SMART_NUMBER
  truncateXAxis: true
  y_axis_bounds:
  - null
  - null
  rich_tooltip: true
  showTooltipTotal: true
  showTooltipPercentage: true
  tooltipSortByMetric: false
  tooltipTimeFormat: smart_date
  extra_form_data: {}
  dashboards:
  - 1
query_context: '{"datasource":{"id":1,"type":"table"},"force":false,"queries":[{"filters":[{"col":"date","op":"TEMPORAL_RANGE","val":"No
  filter"}],"extras":{"having":"","where":""},"applied_time_extras":{},"columns":[{"columnType":"BASE_AXIS","sqlExpression":"day_name","label":"day_name","expressionType":"SQL"}],"metrics":[{"aggregate":"COUNT","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"amount","description":null,"expression":"","filterable":true,"groupby":true,"id":13,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"DECIMAL","type_generic":0,"verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":false,"label":"COUNT(amount)","optionName":"metric_6efvc4reoji_dszmsh7t3un","sqlExpression":null}],"orderby":[[{"aggregate":"COUNT","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"amount","description":null,"expression":"","filterable":true,"groupby":true,"id":13,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"DECIMAL","type_generic":0,"verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":false,"label":"COUNT(amount)","optionName":"metric_xzyztao0twa_acxudg9kwz","sqlExpression":null},false]],"annotation_layers":[],"row_limit":10000,"series_columns":[],"series_limit":0,"series_limit_metric":{"aggregate":"COUNT","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"amount","description":null,"expression":"","filterable":true,"groupby":true,"id":13,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"DECIMAL","type_generic":0,"verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":false,"label":"COUNT(amount)","optionName":"metric_xzyztao0twa_acxudg9kwz","sqlExpression":null},"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{},"time_offsets":[],"post_processing":[{"operation":"pivot","options":{"index":["day_name"],"columns":[],"aggregates":{"COUNT(amount)":{"operator":"mean"}},"drop_missing_columns":false}},{"operation":"sort","options":{"by":"COUNT(amount)","ascending":false}},{"operation":"flatten"}]}],"form_data":{"datasource":"1__table","viz_type":"echarts_timeseries_bar","slice_id":7,"x_axis":"day_name","xAxisForceCategorical":true,"x_axis_sort":"COUNT(amount)","x_axis_sort_asc":false,"metrics":[{"aggregate":"COUNT","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"amount","description":null,"expression":"","filterable":true,"groupby":true,"id":13,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"DECIMAL","type_generic":0,"verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":false,"label":"COUNT(amount)","optionName":"metric_6efvc4reoji_dszmsh7t3un","sqlExpression":null}],"groupby":[],"adhoc_filters":[{"clause":"WHERE","comparator":"No
  filter","expressionType":"SIMPLE","operator":"TEMPORAL_RANGE","subject":"date"}],"timeseries_limit_metric":{"aggregate":"COUNT","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"amount","description":null,"expression":"","filterable":true,"groupby":true,"id":13,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"DECIMAL","type_generic":0,"verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":false,"label":"COUNT(amount)","optionName":"metric_xzyztao0twa_acxudg9kwz","sqlExpression":null},"order_desc":true,"row_limit":10000,"truncate_metric":true,"show_empty_columns":true,"annotation_layers":[],"orientation":"vertical","x_axis_title":"Day
  of the Week","x_axis_title_margin":30,"y_axis_title":"#Transactions","y_axis_title_margin":30,"y_axis_title_position":"Left","sort_series_type":"sum","color_scheme":"redToYellow","show_value":true,"show_legend":false,"x_axis_time_format":"smart_date","y_axis_format":"SMART_NUMBER","truncateXAxis":true,"y_axis_bounds":[null,null],"rich_tooltip":true,"showTooltipTotal":true,"showTooltipPercentage":true,"tooltipSortByMetric":false,"tooltipTimeFormat":"smart_date","extra_form_data":{},"dashboards":[1],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: 951bb8d4-c878-4221-8660-678da60d83f8
version: 1.0.0
dataset_uuid: 4afb8409-9d20-49b2-8791-d74b58810204
