slice_name: TxCompletedToAll30d
description: null
certified_by: null
certification_details: null
viz_type: big_number_total
params:
  datasource: 4__table
  viz_type: big_number_total
  slice_id: 11
  metric:
    aggregate: MAX
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: completed_ratio_30d
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 16
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: DECIMAL
      type_generic: 0
      verbose_name: null
      warning_markdown: null
    datasourceWarning: false
    expressionType: SIMPLE
    hasCustomLabel: false
    label: MAX(completed_ratio_30d)
    optionName: metric_pcjvgb2s4ce_l8wigo0ad9s
    sqlExpression: null
  adhoc_filters: []
  subheader: Status - Completed to All 30d (%)
  header_font_size: 0.2
  subheader_font_size: 0.125
  y_axis_format: SMART_NUMBER
  time_format: smart_date
  conditional_formatting:
  - colorScheme: '#439066'
    column: MAX(completed_ratio_30d)
    operator: '>'
    targetValue: 80
  extra_form_data: {}
  dashboards:
  - 1
  annotation_layers: []
query_context: '{"datasource":{"id":4,"type":"table"},"force":false,"queries":[{"filters":[],"extras":{"having":"","where":""},"applied_time_extras":{},"columns":[],"metrics":[{"aggregate":"MAX","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"completed_ratio_30d","description":null,"expression":null,"filterable":true,"groupby":true,"id":16,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"DECIMAL","type_generic":0,"verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":false,"label":"MAX(completed_ratio_30d)","optionName":"metric_pcjvgb2s4ce_l8wigo0ad9s","sqlExpression":null}],"annotation_layers":[],"series_limit":0,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{}}],"form_data":{"datasource":"4__table","viz_type":"big_number_total","slice_id":11,"metric":{"aggregate":"MAX","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"completed_ratio_30d","description":null,"expression":null,"filterable":true,"groupby":true,"id":16,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"DECIMAL","type_generic":0,"verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":false,"label":"MAX(completed_ratio_30d)","optionName":"metric_pcjvgb2s4ce_l8wigo0ad9s","sqlExpression":null},"adhoc_filters":[],"subheader":"Status
  - Completed to All 30d (%)","header_font_size":0.2,"subheader_font_size":0.125,"y_axis_format":"SMART_NUMBER","time_format":"smart_date","conditional_formatting":[{"colorScheme":"#439066","column":"MAX(completed_ratio_30d)","operator":">","targetValue":80}],"extra_form_data":{},"dashboards":[1],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: f226d941-13f4-4971-a210-c31d546eb778
version: 1.0.0
dataset_uuid: 4556d4e9-844f-48c1-aa97-bc782f16ff3f
