slice_name: UserViolationPerDay
description: null
certified_by: null
certification_details: null
viz_type: echarts_timeseries_line
params:
  datasource: 11__table
  viz_type: echarts_timeseries_line
  slice_id: 28
  x_axis: transaction_date
  time_grain_sqla: P1D
  metrics:
  - aggregate: COUNT
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: violation_severity
      description: null
      expression: ''
      filterable: true
      groupby: true
      id: 51
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: STRING
      type_generic: 1
      verbose_name: null
      warning_markdown: null
    datasourceWarning: false
    expressionType: SIMPLE
    hasCustomLabel: false
    label: COUNT(violation_severity)
    optionName: metric_jtrdv4m1txj_wjtapo9qym
    sqlExpression: null
  groupby:
  - sender
  adhoc_filters:
  - clause: WHERE
    comparator: No filter
    expressionType: SIMPLE
    operator: TEMPORAL_RANGE
    subject: transaction_date
  row_limit: 1000
  truncate_metric: true
  show_empty_columns: true
  comparison_type: values
  annotation_layers: []
  forecastPeriods: 10
  forecastInterval: 0.8
  x_axis_title: YYYY-MM-DD
  x_axis_title_margin: 30
  y_axis_title: '# Violations'
  y_axis_title_margin: 15
  y_axis_title_position: Top
  sort_series_type: sum
  color_scheme: redToYellow
  seriesType: middle
  only_total: true
  area: true
  opacity: 0.2
  markerSize: 6
  zoomable: true
  minorTicks: false
  show_legend: true
  legendType: scroll
  legendOrientation: top
  x_axis_time_format: smart_date
  rich_tooltip: true
  showTooltipTotal: true
  showTooltipPercentage: true
  tooltipTimeFormat: smart_date
  y_axis_format: SMART_NUMBER
  truncateXAxis: true
  y_axis_bounds:
  - null
  - null
  extra_form_data: {}
  dashboards:
  - 3
query_context: '{"datasource":{"id":11,"type":"table"},"force":false,"queries":[{"filters":[{"col":"transaction_date","op":"TEMPORAL_RANGE","val":"No
  filter"}],"extras":{"time_grain_sqla":"P1D","having":"","where":""},"applied_time_extras":{},"columns":[{"timeGrain":"P1D","columnType":"BASE_AXIS","sqlExpression":"transaction_date","label":"transaction_date","expressionType":"SQL"},"sender"],"metrics":[{"aggregate":"COUNT","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"violation_severity","description":null,"expression":"","filterable":true,"groupby":true,"id":51,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"STRING","type_generic":1,"verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":false,"label":"COUNT(violation_severity)","optionName":"metric_jtrdv4m1txj_wjtapo9qym","sqlExpression":null}],"orderby":[[{"aggregate":"COUNT","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"violation_severity","description":null,"expression":"","filterable":true,"groupby":true,"id":51,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"STRING","type_generic":1,"verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":false,"label":"COUNT(violation_severity)","optionName":"metric_jtrdv4m1txj_wjtapo9qym","sqlExpression":null},false]],"annotation_layers":[],"row_limit":1000,"series_columns":["sender"],"series_limit":0,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{},"time_offsets":[],"post_processing":[{"operation":"pivot","options":{"index":["transaction_date"],"columns":["sender"],"aggregates":{"COUNT(violation_severity)":{"operator":"mean"}},"drop_missing_columns":false}},{"operation":"rename","options":{"columns":{"COUNT(violation_severity)":null},"level":0,"inplace":true}},{"operation":"flatten"}]}],"form_data":{"datasource":"11__table","viz_type":"echarts_timeseries_line","slice_id":28,"x_axis":"transaction_date","time_grain_sqla":"P1D","metrics":[{"aggregate":"COUNT","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"violation_severity","description":null,"expression":"","filterable":true,"groupby":true,"id":51,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"STRING","type_generic":1,"verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":false,"label":"COUNT(violation_severity)","optionName":"metric_jtrdv4m1txj_wjtapo9qym","sqlExpression":null}],"groupby":["sender"],"adhoc_filters":[{"clause":"WHERE","comparator":"No
  filter","expressionType":"SIMPLE","operator":"TEMPORAL_RANGE","subject":"transaction_date"}],"row_limit":1000,"truncate_metric":true,"show_empty_columns":true,"comparison_type":"values","annotation_layers":[],"forecastPeriods":10,"forecastInterval":0.8,"x_axis_title":"YYYY-MM-DD","x_axis_title_margin":30,"y_axis_title":"#
  Violations","y_axis_title_margin":15,"y_axis_title_position":"Top","sort_series_type":"sum","color_scheme":"redToYellow","seriesType":"middle","only_total":true,"area":true,"opacity":0.2,"markerSize":6,"zoomable":true,"minorTicks":false,"show_legend":true,"legendType":"scroll","legendOrientation":"top","x_axis_time_format":"smart_date","rich_tooltip":true,"showTooltipTotal":true,"showTooltipPercentage":true,"tooltipTimeFormat":"smart_date","y_axis_format":"SMART_NUMBER","truncateXAxis":true,"y_axis_bounds":[null,null],"extra_form_data":{},"dashboards":[3],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: 693380ed-c34d-43d8-9bd9-e025b8200bf0
version: 1.0.0
dataset_uuid: 8abaf12b-15eb-4b98-bbf6-61a692e508ca
