[project]
name = "common-models"
version = "1.0.0"
description = "Shared Pydantic models for Common Data Model"
requires-python = ">=3.12"

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"